# Generated by Django 4.0.5 on 2022-06-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('reporter', models.CharField(max_length=255)),
                ('news_image', models.ImageField(upload_to='imagenews/')),
                ('description', models.TextField()),
                ('main_text', models.TextField()),
                ('news_quotes', models.TextField()),
                ('author_quote', models.CharField(max_length=255)),
                ('posted', models.DateTimeField()),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorynews', to='categories.category')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
