# Generated by Django 4.0.5 on 2022-06-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='posted',
        ),
    ]
