# Generated by Django 4.0.5 on 2022-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
