# Generated by Django 4.0.5 on 2022-06-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Субкатегория',
                'verbose_name_plural': 'Субкатегории',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_image')),
                ('description', models.TextField()),
                ('quotes', models.TextField()),
                ('subcategory', models.ManyToManyField(related_name='sub_category', to='categories.subcategory', verbose_name='Субкатегории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории ',
            },
        ),
    ]
