# Generated by Django 4.0.5 on 2022-06-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquirements', models.TextField()),
            ],
            options={
                'verbose_name': 'Приобретение знания',
                'verbose_name_plural': 'Приобретения знаний',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_image', models.ImageField(upload_to='team_image/')),
                ('spendtime', models.CharField(max_length=255)),
                ('students', models.CharField(max_length=255)),
                ('about_course', models.TextField()),
                ('raiting', models.IntegerField()),
                ('price', models.IntegerField()),
                ('price_info', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_features', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Характеристика курсов',
                'verbose_name_plural': 'Характеристики курсов',
            },
        ),
        migrations.CreateModel(
            name='SubCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcourse', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подкурс',
                'verbose_name_plural': 'Подкурсы',
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comment', to='courses.course')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
