# Generated by Django 4.0.5 on 2022-06-05 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='acquirements',
            field=models.ManyToManyField(related_name='acquirement', to='courses.acquiredknowledge', verbose_name='Приобретение знания'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curscategory', to='categories.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(to='courses.subcourses', verbose_name='Подкурсы'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_features',
            field=models.ManyToManyField(related_name='course_feature', to='courses.coursefeatures', verbose_name='Характеристики курсов'),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
        ),
    ]
